package br.com.vieirabarbosa.grade.enums;

public enum GradeEnum {
	PRIMEIRA_SERIE("ENSINO_FUNDAMENTAL"),
	SEGUNDA_SERIE("ENSINO_FUNDAMENTAL"),
	TERCEIRA_SERIE("ENSINO_FUNAMENTAL"),
	QUARTA_SERIE("ENSINO_FUNAMENTAL"),
	QUINTA_SERIE("ENSINO_FUNAMENTAL"),
	SEXTA_SERIE("ENSINO_BASICO"),
	SETIMA_SERIE("ENSINO_BASICO"),
	OITAVA_SERIE("ENSINO_BASICO"),
	NOVA_SERIE("ENSINO_BASICO"),
	PRIMEIRO_COLEGIAL("ENSINO_MEDIO"),
	SEGUNDO_COLEGIAL("ENSINO_MEDIO"),
	TERCEIRO_COLEGIAL("ENSINO_MEDIO"),
	PRIMEIRO_COLEGIAL_TEC("ENSINO_TECNICO"),
	SEGUNDO_COLEGIAL_TEC("ENSINO_TECNICO"),
	TERCEIRO_COLEGIAL_TEC("ENSINO_TECNICO");
	private String ciclo;
	public String getCiclo() { return ciclo; }
	GradeEnum(String ciclo) { this.ciclo = ciclo; }
}